steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_FULL_IMAGE_PATH}', '.']

images:
- '${_FULL_IMAGE_PATH}'

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/${_BUILD_SA_EMAIL}'
logsBucket: 'gs://${_LOGS_BUCKET_NAME}/logs'

substitutions:
  _FULL_IMAGE_PATH: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/workstation-image/workstation-image:${SHORT_SHA}'
  _LOGS_BUCKET_NAME: '${PROJECT_ID}-cloudbuild-logs'
  _BUILD_SA_EMAIL: 'cloud-build-sa@${PROJECT_ID}.iam.gserviceaccount.com'
