steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_REPO_PATH}:${SHORT_SHA}', '-t', '${_IMAGE_REPO_PATH}:latest', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['workstations',
         'configs',
         'update',
         'base-config',
         '--region=${LOCATION}',
         '--cluster=cluster',
         '--container-custom-image=${_IMAGE_REPO_PATH}:${SHORT_SHA}']

images:
- '${_IMAGE_REPO_PATH}:${SHORT_SHA}'
- '${_IMAGE_REPO_PATH}:latest'

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/${_BUILD_SA_EMAIL}'
logsBucket: 'gs://${_LOGS_BUCKET_NAME}/logs'

substitutions:
  _IMAGE_REPO_PATH: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/workstation-image/workstation-image'
  _LOGS_BUCKET_NAME: '${PROJECT_ID}-cloudbuild-logs'
  _BUILD_SA_EMAIL: 'cloud-build-sa@${PROJECT_ID}.iam.gserviceaccount.com'
